import type { Printable } from "@/lib/types";

export const printables: Printable[] = [
  {
    slug: "farm-friends-coloring-pack",
    title: "Farm Friends Coloring Pack",
    ageBand: "2-4",
    pages: 8,
    gated: false,
    fileUrl: "/printables/farm-friends-coloring-pack.pdf",
    gradient: "linear-gradient(135deg,#88A98C,#46604E)",
  },
  {
    slug: "first-words-tracing",
    title: "First Words Tracing Sheets",
    ageBand: "2-4",
    pages: 6,
    gated: false,
    fileUrl: "/printables/first-words-tracing.pdf",
    gradient: "linear-gradient(135deg,#E0A86B,#C9573E)",
  },
  {
    slug: "seasons-sorting-mats",
    title: "Seasons Sorting Mats",
    ageBand: "5-7",
    pages: 10,
    gated: true,
    fileUrl: "/printables/seasons-sorting-mats.pdf",
    gradient: "linear-gradient(135deg,#E7C46A,#C99A33)",
  },
  {
    slug: "feelings-faces-flashcards",
    title: "Feelings Faces Flashcards",
    ageBand: "5-7",
    pages: 12,
    gated: true,
    fileUrl: "/printables/feelings-faces-flashcards.pdf",
    gradient: "linear-gradient(135deg,#C9A8D4,#7A5C8E)",
  },
  {
    slug: "story-map-worksheet",
    title: "Build-a-Story Map Worksheet",
    ageBand: "8-10",
    pages: 4,
    gated: false,
    fileUrl: "/printables/story-map-worksheet.pdf",
    gradient: "linear-gradient(135deg,#7FA8B8,#3F6E7A)",
  },
  {
    slug: "fossil-dig-journal",
    title: "Fossil Dig Field Journal",
    ageBand: "8-10",
    pages: 14,
    gated: true,
    fileUrl: "/printables/fossil-dig-journal.pdf",
    gradient: "linear-gradient(135deg,#9CB87F,#46604E)",
  },
  {
    slug: "bedtime-reading-chart",
    title: "Bedtime Reading Reward Chart",
    ageBand: "2-4",
    pages: 2,
    gated: false,
    fileUrl: "/printables/bedtime-reading-chart.pdf",
    gradient: "linear-gradient(135deg,#8FB6A5,#3F7A6B)",
  },
  {
    slug: "nature-scavenger-hunt",
    title: "Backyard Nature Scavenger Hunt",
    ageBand: "5-7",
    pages: 3,
    gated: true,
    fileUrl: "/printables/nature-scavenger-hunt.pdf",
    gradient: "linear-gradient(135deg,#9CB87F,#5C7A4A)",
  },
];
